### PR TITLE
Docs typo fix

### PR DESCRIPTION
**Pull request by BryceGattis**
## Description

Small typo fix in docs.

- [ ] I have updated the release notes.
- [x] I have updated all relevant user documentation.

### CODE REVIEW

**Review by feltech — APPROVED** [review]
Good spot and thanks for the fix!

Only minor comment really is (as per [the docs](https://github.com/OpenAssetIO/OpenAssetIO/blob/main/doc/contributing/COMMITS.md)) it would be good to add a `[Docs]` tag preceding the commit message.

**Comment by BryceGattis** [comment]
@feltech Should I try to amend the commit to fix that?

**Comment by feltech** [comment]
> @feltech Should I try to amend the commit to fix that?

We would have merged this regardless.  However, since this PR needs rebasing against `main` anyway, it would be great if you could update the commit message at the same time, but not a big deal.

**Comment by feltech** [comment]
@BryceGattis I just noticed you gave us permission to update your branch, so I've taken the liberty of rebasing, and finessing the commit message a bit.

**Pull request merged**
