### PR TITLE
[CI] Add `black` Python formatting check

### LINKED ISSUE #577: [Python] Use `black` and check in CI
## ACs

- `black` format codebase.
- [ideally] Add a CMake check, or a CI check if not.

### PR DESCRIPTION
**Pull request by feltech**
Closes #577

### CODE REVIEW

**Review by foundrytom — CHANGES_REQUESTED** [review]
This is going to be great to have!

- Can we move the CI check to the end, so it's not broken in a bisect.
- I think we should call this out in Release Notes (improvements?)
- Updated `CODING_STANDARDS.md`

**Comment by foundrytom** [comment]
Is there some way we can https://akrabat.com/ignoring-revisions-with-git-blame/ and have it come with a checkout?

**Comment by feltech** [comment]
> Is there some way we can https://akrabat.com/ignoring-revisions-with-git-blame/ and have it come with a checkout?

That's cool, but personally I was surprised by how few changes `black` reformatting caused.  Do you think it's still worth spending the time to add a revision ignore file?  Happy to do it if you think it's worthwhile.

**Comment by foundrytom** [comment]
> > Is there some way we can https://akrabat.com/ignoring-revisions-with-git-blame/ and have it come with a checkout?
> 
> That's cool, but personally I was surprised by how few changes `black` reformatting caused. Do you think it's still worth spending the time to add a revision ignore file? Happy to do it if you think it's worthwhile.

Yeah, you're right, let's leave it for now.

**Comment by feltech** [comment]
>     * Can we move the CI check to the end, so it's not broken in a bisect.

Done, took the liberty of force-pushing, new CI commit is 9dc3dde9

>     * I think we should call this out in `RELEASE_NOTES.md` (improvements?)

Added in 212c4b76

>     * Update ~`CODING_STANDARDS.md`~ `CODING_STYLE.md`

Added in 72a3a07a

**Review by foundrytom — APPROVED** [review]
Perfect, thanks! FFTSQMAYL

**Pull request merged**
